import { StylePack } from './types'

export const STYLE_PACKS: StylePack[] = [
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean white canvas, content first — let the results speak.',
    preview: { bg: '#FFFFFF', text: '#111111', primary: '#111111', accent: '#F5F5F5' },
    css: {
      '--color-bg': '#FFFFFF',
      '--color-surface': '#F9F9F9',
      '--color-text': '#111111',
      '--color-text-muted': '#777777',
      '--color-primary': '#111111',
      '--color-primary-hover': '#333333',
      '--color-accent': '#F5F5F5',
      '--color-border': '#E5E5E5',
      '--radius-btn': '4px',
      '--radius-card': '8px',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
    },
  },
  {
    id: 'tech-dark',
    name: 'Tech Dark',
    description: 'Deep dark background, vibrant cyan highlights. Modern AI aesthetic.',
    preview: { bg: '#0A0E1A', text: '#E8F4FF', primary: '#00D4FF', accent: '#1A2035' },
    css: {
      '--color-bg': '#0A0E1A',
      '--color-surface': '#111827',
      '--color-text': '#E8F4FF',
      '--color-text-muted': '#8899AA',
      '--color-primary': '#00D4FF',
      '--color-primary-hover': '#00B8E0',
      '--color-accent': '#1A2035',
      '--color-border': '#1E2D45',
      '--radius-btn': '6px',
      '--radius-card': '12px',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
    },
  },
  {
    id: 'bold-energetic',
    name: 'Bold & Energetic',
    description: 'High-saturation, big type, strong contrast. Made to grab attention.',
    preview: { bg: '#FFFBF5', text: '#1A0A00', primary: '#FF4D00', accent: '#FFF3EC' },
    css: {
      '--color-bg': '#FFFBF5',
      '--color-surface': '#FFF3EC',
      '--color-text': '#1A0A00',
      '--color-text-muted': '#7A4030',
      '--color-primary': '#FF4D00',
      '--color-primary-hover': '#E04400',
      '--color-accent': '#FFE8D6',
      '--color-border': '#FFD5BC',
      '--radius-btn': '2px',
      '--radius-card': '4px',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
    },
  },
  {
    id: 'clean-professional',
    name: 'Clean Professional',
    description: 'Neutral greys, structured grid, trustworthy enterprise feel.',
    preview: { bg: '#F8F9FC', text: '#1E2533', primary: '#2563EB', accent: '#EEF2FF' },
    css: {
      '--color-bg': '#F8F9FC',
      '--color-surface': '#FFFFFF',
      '--color-text': '#1E2533',
      '--color-text-muted': '#64748B',
      '--color-primary': '#2563EB',
      '--color-primary-hover': '#1D4ED8',
      '--color-accent': '#EEF2FF',
      '--color-border': '#E2E8F0',
      '--radius-btn': '8px',
      '--radius-card': '12px',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
    },
  },
  {
    id: 'soft-friendly',
    name: 'Soft & Friendly',
    description: 'Warm pastels, large roundness, gentle and approachable.',
    preview: { bg: '#FDF8FF', text: '#2D1B4E', primary: '#8B5CF6', accent: '#F5F0FF' },
    css: {
      '--color-bg': '#FDF8FF',
      '--color-surface': '#F5F0FF',
      '--color-text': '#2D1B4E',
      '--color-text-muted': '#7C6A9A',
      '--color-primary': '#8B5CF6',
      '--color-primary-hover': '#7C3AED',
      '--color-accent': '#EDE9FE',
      '--color-border': '#DDD6FE',
      '--radius-btn': '999px',
      '--radius-card': '20px',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
    },
  },
]

export function getStylePack(id: string): StylePack {
  return STYLE_PACKS.find(s => s.id === id) ?? STYLE_PACKS[3]
}
